image: wjdp/xsacdb-image:v0.4.0-1

variables:
  POSTGRES_DB: xsacdb
  POSTGRES_USER: runner
  POSTGRES_PASSWORD: ""

before_script:
  - locale
  - export XSACDB_ENVIRONMENT=TEST

stages:
  - prepare
  - build
  - test
  - deploy

pip:
  stage: prepare
  script:
    - virtualenv env
    - source env/bin/activate
    - pip install https://github.com/philippbosch/django-geoposition/archive/django-1.11.zip
    - pip install -r requirements.txt
  cache:
    paths:
      - env/
  artifacts:
    paths:
      - env/
  tags:
    - docker

frontend:
  stage: prepare
  script:
    - bower install --allow-root
    - rm -rf lib/tether/examples
    - npm install
  cache:
    paths:
      - lib/
      - node_modules/
  artifacts:
    paths:
      - lib/
      - node_modules/
  tags:
    - docker

data:
  stage: prepare
  script:
    - mkdir tmp
    - curl $BSAC_DATA > tmp/bsac_data.yaml
  artifacts:
    paths:
      - tmp/bsac_data.yaml
  tags:
    - docker

check:
  stage: test
  script:
    - source env/bin/activate
    - src/manage.py check
  tags:
    - docker

static:
  stage: build
  services:
    - postgres:latest
    - redis:latest
  script:
    - gulp deploy
    - source env/bin/activate
    - src/manage.py collectstatic --noinput
  artifacts:
    paths:
      - dist/
  tags:
    - docker

test:
  stage: test
  services:
    - postgres:latest
    - redis:latest
  script:
    - source env/bin/activate
    - coverage run --include=src/\* --omit=\*/migrations/\*  src/manage.py test xSACdb xsd_about xsd_auth xsd_frontend xsd_help xsd_kit xsd_members xsd_sites xsd_training xsd_trips
    - coverage report --skip-covered
    - coverage xml
    - pip install codacy-coverage
    - python-codacy-coverage -r coverage.xml
  tags:
    - docker

deploy-current:
  stage: deploy
  only:
    - master
  script:
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H "$DEPLOY_HOST" >> ~/.ssh/known_hosts
    - git push dokku@$DEPLOY_HOST:xsacdb-current HEAD:master -f
  environment:
    name: xsacdb-current
    url: https://current.xsacdb.wjdp.uk
  tags:
    - docker

deploy-next:
  stage: deploy
  only:
    - develop
  script:
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H "$DEPLOY_HOST" >> ~/.ssh/known_hosts
    - git push dokku@$DEPLOY_HOST:xsacdb-next HEAD:master -f
  environment:
    name: xsacdb-next
    url: https://next.xsacdb.wjdp.uk
  tags:
    - docker
