image: wjdp/xsacdb-image:v0.2.0-4

services:
  - postgres:latest
  - redis:latest

variables:
  POSTGRES_DB: xsacdb
  POSTGRES_USER: runner
  POSTGRES_PASSWORD: ""

before_script:
  - locale
  - export XSACDB_ENVIRONMENT=TEST

cache:
  paths:
    - env/
    - lib/

stages:
  - prepare
  - build
  - test

pip:
  stage: prepare
  script:
    - virtualenv env
    - source env/bin/activate
    - pip install -qr requirements.txt
  artifacts:
    paths:
      - env/
  tags:
    - docker

bower:
  stage: prepare
  script:
    - bower install -q --allow-root
    - rm -rf lib/tether/examples
  artifacts:
    paths:
      - lib/
  tags:
    - docker

data:
  stage: prepare
  script:
    - mkdir tmp
    - curl $BSAC_DATA > tmp/bsac_data.yaml
  artifacts:
    paths:
      - tmp/bsac_data.yaml
  tags:
    - docker

check:
  stage: build
  script:
    - source env/bin/activate
    - src/manage.py check
  tags:
    - docker

static:
  stage: build
  script:
    - source env/bin/activate
    - src/manage.py collectstatic --noinput
    - src/manage.py compress
  artifacts:
    paths:
      - dist/
  tags:
    - docker

test:
  stage: test
  script:
    - source env/bin/activate
    - src/manage.py migrate
    - src/manage.py test xSACdb xsd_about xsd_auth xsd_frontend xsd_help xsd_kit xsd_members xsd_sites xsd_training xsd_trips
  tags:
    - docker
