variables:
  POSTGRES_DB: xsacdb
  POSTGRES_USER: runner
  POSTGRES_PASSWORD: ""
  BSAC_DATA: "https://s3.amazonaws.com/xsacdb-bsac-data/bsac_data.yaml"
  DOCKER_DRIVER: overlay2

stages:
  - build
  - test
  - deploy

build:
  stage: build
  image: docker:19.03.1
  services:
    - docker:19.03.1-dind
  before_script:
    - apk add git
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE/ci:$CI_COMMIT_REF_SLUG || docker pull wjdp/xsacdb:next || true
  script:
    - git describe
    - docker build
        --cache-from $CI_REGISTRY_IMAGE/ci:$CI_COMMIT_REF_SLUG
        --cache-from docker.io/wjdp/xsacdb:next
        -t $CI_REGISTRY_IMAGE/ci:$CI_COMMIT_REF_SLUG
        --build-arg VCS_REV=$(git describe)
        .
    - docker push $CI_REGISTRY_IMAGE/ci:$CI_COMMIT_REF_SLUG

django-test:
  stage: test
  image: $CI_REGISTRY_IMAGE/ci:$CI_COMMIT_REF_SLUG
  variables:
    GIT_STRATEGY: none
    XSACDB_ENVIRONMENT: TEST
    XSACDB_XMLTESTRUNNER: 1
  services:
    - postgres:latest
    - redis:latest
  before_script:
    - cd /app
    - mkdir tmp
    - curl $BSAC_DATA > tmp/bsac_data.yaml
  script:
    - src/manage.py check
    - src/manage.py test xSACdb xsd_about xsd_auth xsd_frontend xsd_help xsd_kit xsd_members xsd_sites xsd_training xsd_trips
  after_script:
    - mv /app/junit-django.xml $CI_PROJECT_DIR
  artifacts:
    paths:
      - junit-django.xml
    reports:
      junit: junit-django.xml

eslint:
  stage: test
  image: $CI_REGISTRY_IMAGE/ci:$CI_COMMIT_REF_SLUG
  variables:
    GIT_STRATEGY: none
  before_script:
    - cd /app
  script:
    - npm run lint:junit
  after_script:
    - mv /app/junit-eslint.xml $CI_PROJECT_DIR
  artifacts:
    paths:
      - junit-eslint.xml
    reports:
      junit: junit-eslint.xml

deploy-next:
  stage: deploy
  image: docker:19.03.1
  variables:
    GIT_STRATEGY: none
  services:
    - docker:19.03.1-dind
  before_script:
    - docker pull $CI_REGISTRY_IMAGE/ci:$CI_COMMIT_REF_SLUG
    - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_TOKEN
  script:
    - docker tag $CI_REGISTRY_IMAGE/ci:$CI_COMMIT_REF_SLUG wjdp/xsacdb:next
    - docker push wjdp/xsacdb:next
  only:
    - master
