image: wjdp/flatcar

services:
  - postgres

before_script:
  - virtualenv env
  - source env/bin/activate
  - pip install -r requirements.txt
  - bower install --allow-root
  - cp src/local_settings.py.example src/local_settings.py

stages:
  - test

django-validate:
  stage: test
  script:
    - source env/bin/activate
    - src/manage.py validate

django-check:
  stage: test
  script:
    - source env/bin/activate
    - src/manage.py check

django-test:
  stage: test
  script:
    - source env/bin/activate
    - src/manage.py test xSACdb xsd_about xsd_auth xsd_frontend xsd_help xsd_kit xsd_members xsd_sites xsd_training xsd_trips
