image: wjdp/xsacdb:py3

variables:
  POSTGRES_DB: xsacdb
  POSTGRES_USER: runner
  POSTGRES_PASSWORD: ""
  BSAC_DATA: "https://s3.amazonaws.com/xsacdb-bsac-data/bsac_data.yaml"
  DOCKER_DRIVER: overlay2

stages:
  - build
  - test
  - docker
  - deploy

static:
  stage: build
  before_script:
    - export XSACDB_ENVIRONMENT=TEST
    - pipenv install --deploy --system
    - npm install
  script:
    - gulp deploy
    - src/manage.py collectstatic --noinput
  artifacts:
    paths:
      - dist/
      - lib/

check:
  stage: test
  before_script:
    - export XSACDB_ENVIRONMENT=TEST
    - pipenv install --deploy --system
  script:
    - src/manage.py check

test:
  stage: test
  services:
    - postgres:latest
    - redis:latest
  before_script:
    - export XSACDB_ENVIRONMENT=TEST
    - locale
    - pipenv install --deploy --system
    - mkdir tmp
    - curl $BSAC_DATA > tmp/bsac_data.yaml
  script:
    - coverage run --include=src/\* --omit=\*/migrations/\*  src/manage.py test xSACdb xsd_about xsd_auth xsd_frontend xsd_help xsd_kit xsd_members xsd_sites xsd_training xsd_trips
    - coverage report --skip-covered
    - coverage xml
    - pip3 install codacy-coverage
    - python-codacy-coverage -r coverage.xml

docker-build-next:
  image: docker
  stage: docker
  services:
    - docker:dind
  before_script:
    - docker pull wjdp/xsacdb:next || true
    - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_TOKEN
  script:
    - docker build --cache-from wjdp/xsacdb:next -t wjdp/xsacdb:next .
    - docker push wjdp/xsacdb:next
  only:
    - master

#deploy-current:
#  stage: deploy
#  only:
#    - master
#  script:
#    - mkdir -p ~/.ssh
#    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
#    - ssh-keyscan -H "$DEPLOY_HOST" >> ~/.ssh/known_hosts
#    - git push dokku@$DEPLOY_HOST:xsacdb-current HEAD:master -f
#  environment:
#    name: xsacdb-current
#    url: https://current.xsacdb.wjdp.uk
#  tags:
#    - docker
#
#deploy-next:
#  stage: deploy
#  only:
#    - develop
#  script:
#    - mkdir -p ~/.ssh
#    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
#    - ssh-keyscan -H "$DEPLOY_HOST" >> ~/.ssh/known_hosts
#    - git push dokku@$DEPLOY_HOST:xsacdb-next HEAD:master -f
#  environment:
#    name: xsacdb-next
#    url: https://next.xsacdb.wjdp.uk
#  tags:
#    - docker
