image: wjdp/flatcar

services:
  - postgres

# before_script:


stages:
  - build
  - test
  # - deploy

python:
  stage: build
  script:
    - virtualenv env
    - source env/bin/activate
    - pip install -r requirements.txt

frontend:
  stage: build
  script:
    - bower install --allow-root

django:
  stage: test
  script:
    - src/manage.py test
