image: wjdp/flatcar

services:
  - postgres

before_script:
  - virtualenv env
  - source env/bin/activate
  - echo "pip install"
  - pip install -q -r requirements.txt
  - echo "bower install"
  - bower install -q --allow-root
  - mkdir tmp
  - wget $TEST_FIXTURE -O tmp/test_fixture.json

stages:
  - test

django-validate:
  stage: test
  tags:
    - docker
  script:
    - source env/bin/activate
    - src/manage.py validate

django-check:
  stage: test
  tags:
    - docker
  script:
    - source env/bin/activate
    - src/manage.py check

django-test:
  stage: test
  tags:
    - docker
  script:
    - source env/bin/activate
    - src/manage.py test xSACdb xsd_about xsd_auth xsd_frontend xsd_help xsd_kit xsd_members xsd_sites xsd_training xsd_trips
