image: wjdp/xsacdb-image:v0.2.0-3

services:
  - postgres:latest
  - redis:latest

variables:
  POSTGRES_DB: xsacdb
  POSTGRES_USER: runner
  POSTGRES_PASSWORD: ""

before_script:
  - locale
  - export XSACDB_ENVIRONMENT=TEST
  - virtualenv env
  - source env/bin/activate
  - pip install -qr requirements.txt

stages:
  - check
  - test

django-check:
  stage: check
  tags:
    - docker
  script:
    - source env/bin/activate
    - src/manage.py check

django-test:
  stage: test
  tags:
    - docker
  script:
    - bower install -q --allow-root
    - rm -rf lib/tether/examples
    - mkdir tmp
    - curl $BSAC_DATA > tmp/bsac_data.yaml
    - source env/bin/activate
    - src/manage.py migrate
    - src/manage.py collectstatic --noinput
    - src/manage.py compress
    - src/manage.py test xSACdb xsd_about xsd_auth xsd_frontend xsd_help xsd_kit xsd_members xsd_sites xsd_training xsd_trips
