image: wjdp/flatcar

services:
  - postgres

before_script:
  - virtualenv env
  - source env/bin/activate
  - pip install -qr requirements.txt
  - bower install -q --allow-root
  - mkdir tmp
  - wget $BSAC_DATA -O tmp/bsac_data.yaml

stages:
  - test

django-frontend:
  stage: test
  tags:
    - docker
  script:
    - source env/bin/activate
    - src/manage.py collectstatic --noinput

django-check:
  stage: test
  tags:
    - docker
  script:
    - source env/bin/activate
    - src/manage.py check

django-test:
  stage: test
  tags:
    - docker
  script:
    - source env/bin/activate
    - src/manage.py test xSACdb xsd_about xsd_auth xsd_frontend xsd_help xsd_kit xsd_members xsd_sites xsd_training xsd_trips
