# Site settings
title: xSACdb
email: xSACdb@wjdp.uk
description: > # this means to ignore newlines until "baseurl:"
  A web based database for managing BSAC branch clubs.
  Looks after membership details, training records, known sites, kit and
  club trips.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://xSACdb.wjdp.uk" # the base hostname & protocol for your site
gitlab: "https://gitlab.com/wjdp/xSACdb"
github: "https://github.com/wjdp/xSACdb"

# Build settings
markdown: kramdown
permalink: pretty

gems:
- jekyll-sitemap

exclude: [vendor, node_modules]
